hngprojects/hng_boilerplate_nestjs

- .github/ISSUE_TEMPLATE/feat--.md
Reverts hngprojects/hng_boilerplate_nestjs#26
> Revert "Update feat--.md"

- wiki_readme/CICD-Pipeline.md
- wiki_readme/Database-Setup.md
- wiki_readme/Home.md
- wiki_readme/NGINX-Configuration.md
- wiki_readme/RabbitMQ-Installation-and-Setup.md
A wiki docs folder which contained all our wiki docs was added as we were told to await an update from our mentor regarding the permission needed to add these docs directly to the project.
> Added a wiki docs folder

- .env.example
- src/app.module.ts
- src/guards/auth.guard.ts
- src/health.controller.ts
- src/modules/auth/tests/auth.service.spec.ts
- src/modules/user/user.service.ts
**Try accessing a protected route**
- without being authenticated.
- with an expired bearer token
- with an invalid token
**The expected results is to get a 401 Unauthenticated response**
[[FEAT]: Authentication - User Sign Up](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/9)
> feat: Auth guard

- src/app.module.ts
- src/modules/blog/blog.module.ts
- src/modules/blog/controllers/blog.controller.ts
- src/modules/blog/dto/create-blog.dto.ts
- src/modules/blog/entities/blog-category.entity.ts
- src/modules/blog/entities/blog-comments.entity.ts
- src/modules/blog/entities/blog.entity.ts
- src/modules/blog/services/blog.service.ts
- src/modules/blog/tests/blog.controller.spec.ts
- src/modules/blog/tests/blog.service.spec.ts
- src/modules/user/entities/user.entity.ts
This PR adds a new endpoint for creating blog posts in the application. The new feature includes the implementation of the `BlogController`, `BlogService`, and necessary DTOs and entities.
1. Open **Postman**
2. Set the request to **POST**
3. Enter the URL for your API endpoint. ex:  `http://localhost:3000/api/v1/blogs`
```bash 
POST /api/v1/blogs
```
4. Go to the Body tab and select raw. Then set the format to JSON and enter the JSON body with the required fields for CreateBlogDto.
Example:
```json
{
"title": "My First Blog",
"image_url":"https:/example.com/you.jpg",
"content": "This is the content of my first blog post",
"isPublished": true,
"authorId": "authoruid"
"category":"categoryuid"
}
```
5. Click Send you'll get a response depending on the request body
Success Response
```json
{ …
```
> feat: add blog post endpoint feature

- db/migrations/1721879262570-migration.ts
- src/modules/user/entities/user.entity.ts
> fix: Deployment migration error fix

- src/app.e2e.spec.ts
- src/app.module.ts
- src/main.ts
- src/probe.controller.ts
Added a route to return our API name as Mark asked.
> Test: probe

- src/helpers/SystemMessages.ts
- src/modules/auth/auth.controller.ts
- src/modules/auth/auth.service.ts
- src/modules/auth/dto/login-error-dto.ts
- src/modules/auth/tests/auth.service.spec.ts
this is a provisional fix for the google redirect.
> fix: redirect issues

- src/modules/email/email.service.ts
- src/modules/email/templates/register-otp.hbs
Add email template for register email otp
> fix: add email template for register

- src/database/seeding/seeding.service.ts
- src/modules/invite/tests/invite.service.spec.ts
- src/modules/organisations/entities/organisations.entity.ts
- src/modules/organisations/tests/mocks/organisation.mock.ts
- src/modules/product-category/entities/product-category.entity.ts
- src/modules/products/dto/create-product.dto.ts
- src/modules/products/entities/product.entity.ts
- src/modules/products/products.controller.ts
- src/modules/products/products.module.ts
- src/modules/products/products.service.ts
- src/modules/products/tests/mocks/product-request-dto.mock.ts
- src/modules/products/tests/mocks/product.mock.ts
- src/modules/products/tests/products.service.spec.ts
- src/modules/user/entities/user.entity.ts
This PR implements an endpoint for creating a new product:
* Added POST /api/v1/products/:orgId Endpoint: Creates a new products.
* Authentication: Ensures only authenticated users can access these endpoints.
* Authorization: Ensures only owners or admins of an organization can create a new product.
* Validation: Implements input validation for obtained from the client.
* Error Handling: Returns specific HTTP status codes and messages based on various scenarios.
**Success**
```json
{
"status_code": 201,
"message": "Product created successfully",
"data": {
"id": "ecb968ce-f7e0-4ff9-913b-0c8dbe9d3f46",
"name": "Second product",
"description": null,
"price": 45,
"status": "in stock",
"quantity": 7,
"created_at": "2024-07-29T19:51:39.004Z",
"updated_at": …
```
> feat: create product

- package-lock.json
- package.json
- src/modules/auth/auth.controller.ts
- src/modules/auth/auth.module.ts
- src/modules/auth/auth.service.ts
- src/modules/auth/google-auth.service.ts
- src/modules/auth/interfaces/GoogleAuthPayloadInterface.ts
- src/modules/auth/interfaces/GoogleVerificationPayloadInterface.ts
- src/modules/auth/tests/auth.service.spec.ts
-  Updated logic to create and verify user through google auth
- Verified google auth token
> feat: Google Authentication

- src/modules/jobs/jobs.controller.ts
- src/modules/jobs/jobs.service.ts
- src/modules/jobs/tests/jobs.service.spec.ts
- src/modules/jobs/tests/mocks/jobs.mock.ts
- **Action**: Send a GET request to the `GET /api/v1/jobs` endpoint get all jobs.
- **Expected Result**: You should receive a list of all jobs.
**Checklist**
**Reference Issue**
No issue was found for this endpoint 
---
> feat: get all jobs

- src/helpers/SystemMessages.ts
- src/modules/auth/auth.controller.ts
- src/modules/auth/auth.module.ts
- src/modules/auth/auth.service.ts
- src/modules/auth/tests/auth.service.spec.ts
- src/modules/organisations/tests/organisations.service.spec.ts
- src/modules/otp/otp.service.ts
- src/modules/profile/profile.module.ts
- src/modules/testimonials/testimonials.module.ts
- src/modules/testimonials/tests/testimonials.service.spec.ts
- src/modules/timezones/timezones.service.ts
- src/modules/user/dto/user-response.dto.ts
- src/modules/user/tests/user.service.spec.ts
- src/modules/user/user.controller.ts
- src/modules/user/user.module.ts
- src/modules/user/user.service.ts
- Generated user profile on user registration
- Fixed issues with authentication endpoints
- Updated test to match updates
> feat: Fixed magic link implementation issues

- src/helpers/exceptionHandler.ts
- src/modules/auth/auth.controller.ts
- src/modules/auth/auth.service.ts
- src/modules/auth/tests/auth.service.spec.ts
- src/modules/user/interfaces/UserInterface.ts
- src/modules/user/tests/user.service.spec.ts
- src/modules/user/user.service.ts
- src/shared/inteceptors/response.interceptor.ts
- created a custom handler for managing exceptions
- updated response interceptor to fix discrepancies
> feat: Fixed Exception Handling Issues

- src/modules/profile/dto/update-profile.dto.ts
- src/modules/profile/profile.controller.ts
- src/modules/profile/profile.service.ts
- src/modules/profile/tests/profile.service.spec.ts
This PR implements an endpoint for updating user profile:
* Added PATCH /api/v1/profile/:user_id Endpoint: Gets a user profile
* Authentication: Ensures only authenticated users can access these endpoints.
* Authorization: Ensures only users or admin can access this route.
* Error Handling: Returns specific HTTP status codes and messages based on various scenarios.
**Success**
```json
{
"status": 200,
"message": "Profile successfully updated",
"data": {
"id": "41c55648-1a26-4ab0-8941-a7843db1e1bc",
"created_at": "2024-07-29T22:59:10.052Z",
"updated_at": "2024-07-29T22:59:10.052Z",
"username": "Janesmith",
"jobTitle": "",
"pronouns": "",
"dept": "",
"email": "jane.smith@example.com",
"bio": "",
"socialLinks": [""],
"language": "",
"region": "",
"timezones": "",
"profilePicUrl": ""
}
}
``` …
> feat: update profile endpoint

- .github/workflows/dev.yml
- Updated pipeline to run against the head branch
> feat: updated pipeline

- src/app.module.ts
- src/modules/help-center/Tests/help-center.service.spec.ts
- src/modules/help-center/dto/create-help-center.dto.ts
- src/modules/help-center/dto/update-help-center.dto.ts
- src/modules/help-center/entities/help-center.entity.ts
- src/modules/help-center/help-center.controller.ts
- src/modules/help-center/help-center.module.ts
- src/modules/help-center/help-center.service.ts
This PR implements an endpoint for updating help center topics (Admin only):
- **Added PATCH /api/v1/help-center/topics/:id Endpoint:** Allows admin users to update existing topics.
- **Authentication and Authorization:** Requires a JWT token and admin role for access.
- **Response Handling:** Provides appropriate responses for various authorization and validation scenarios.
1. **Login Admin User:**
- Make a `POST` request to `/api/v1/auth/login` with an admin user's credentials.
- Check the response for a valid JWT token.
2. **Update Help Center Topic:**
- Make a `PATCH` request to `/api/v1/help-center/topics/:id` with the topic details in the request body and a valid JWT token in the header.
- Verify the response contains the updated topic details.
3. **Edge Cases:**
- **Invalid …
> feat: update help center topics

- package.json
- src/database/seeding/seeding.service.ts
- src/modules/auth/dto/create-user.dto.ts
- src/modules/notifications/tests/mocks/notification-repo.mock.ts
- src/modules/organisations/tests/mocks/organisation.mock.ts
- src/modules/products/entities/product-variant.entity.ts
- src/modules/products/entities/product.entity.ts
- src/modules/products/products.controller.ts
- src/modules/products/products.service.ts
- src/modules/products/tests/products.service.spec.ts
- src/modules/profile/entities/profile.entity.ts
- src/modules/profile/profile.service.ts
- src/modules/profile/tests/profile.service.spec.ts
- src/modules/user/entities/user.entity.ts
- src/modules/user/options/CreateNewUserOptions.ts
- src/modules/user/user.service.ts
This PR addresses issue #77  by implementing the get, update and delete frequently asked questions operations from the 
database. 
To test this feature, you can send a DELETE request to the following endpoint:
`/api/v1/product/{product-id}`
Endpoint:
DELETE  `/api/v1/product/{product-id}`
Response (Success):
```
{
"status": 200,
"message": "Profile successfully deleted",
"data": {}
}
```
Response (Error - Invalid Request):
```
{
"message": "Bad request",
"status_code": 400
}
```
`Error Handling:`
`Security Measures:`
Reference Issue: [[Link to Issue]](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/77)
> Feat: Delete product by id

- src/database/seeding/seeding.service.ts
- src/modules/auth/dto/create-user.dto.ts
- src/modules/notifications/tests/mocks/notification-repo.mock.ts
- src/modules/organisations/tests/mocks/organisation.mock.ts
- src/modules/profile/entities/profile.entity.ts
- src/modules/profile/profile.service.ts
- src/modules/profile/tests/profile.service.spec.ts
- src/modules/user/entities/user.entity.ts
- src/modules/user/options/CreateNewUserOptions.ts
- src/modules/user/user.service.ts
This PR fixed a bug in  finding a user profile by id and registers an admin user
> fix: find profile by user id, admin user register

- src/modules/help-center/help-center.controller.ts
- Removed swagger authentication from public help routes
> feat: removed swagger authentication from help center public routes

- src/helpers/SystemMessages.ts
- src/modules/help-center/Tests/help-center.service.spec.ts
- src/modules/help-center/dto/help-center.response.dto.ts
- src/modules/help-center/help-center.controller.ts
- src/modules/help-center/help-center.service.spec.ts
- src/modules/help-center/help-center.service.ts
- src/shared/inteceptors/response.interceptor.ts
- fixed issue with help center response body
- properly structured returned data to match the standard
```json 
{ 
status_code: number,
message: string,
data: object | object[]
}
```
> feat: Help center fixes

- src/app.module.ts
> docs(app-module): re-added the comment removed

- src/app.module.ts
- src/modules/teams/dto/create-team.dto.ts
- src/modules/teams/dto/team.response.dto.ts
- src/modules/teams/dto/update-team.dto.ts
- src/modules/teams/entities/team.entity.ts
- src/modules/teams/teams.controller.ts
- src/modules/teams/teams.module.ts
- src/modules/teams/teams.service.ts
- src/modules/teams/tests/teams.service.spec.ts
This PR implements endpoints for newsletter subscription:
* Added` POST /api/v1/teams` Endpoint: Create team members (super admin).
* Added `GET /api/v1/teams` Endpoint: Get all team members.
* Added `GET /api/v1/teams/{id}` Endpoint: Get a single team member.
* Added `PATCH /api/v1/teams/{id}` Endpoint: Update a single team member (super admin).
* Added `DELETE /api/v1/team/{id}` Endpoint: Delete a team member (super admin).
* Error Handling: Returns specific HTTP status codes and messages based on various scenarios.
**Request Body**
```json
{
"name": "string",
"title": "string",
"description": "string",
"image": "string",
"facebook": "string",
"twitter": "string",
"instagram": "string"
}
```
**Success**
```json
{
"id": "string",
"name": "string",
"title": "string",
"description": …
```
> feat: teams

- src/modules/auth/auth.service.ts
- Generates a verification token for the user on registration
> feat: Verification Token

- src/modules/teams/teams.controller.ts
This PR indicates the changes that were made to the `GET` request responses on the teams endpoint.
* Fixed `GET /api/v1/teams` endpoint response
* Fixed `GET /api/v1/teams/{id}` endpoint response
* Updated API documentation to reflect the new endpoint.
**Success**
```json
{
"status": "number",
"message": "string",
"data": [
{
"id": "string",
"name": "string",
"title": "string",
"description": "string",
"image": "string",
"socials": {
"facebook": "string",
"twitter": "string",
"instagram": "string"
}
}
]
}
```
`param`: id (where id = team member's id)
**Success**
```json
{
"status": "number",
"message": "string",
"data": {
"id": "string",
"name": "string",
"title": "string",
"description": "string",
"image": "string",
"socials": {
"facebook": "string",
"twitter": "string",
"instagram": …
```
> fix: teams

- src/modules/auth/auth.controller.ts
- src/modules/auth/auth.service.ts
- src/modules/auth/dto/updatePasswordDto.ts
- src/modules/otp/otp.service.ts
This PR exposes an endpoint for verifying otp and updating password
> feat: endpoint for verifying otp and updating password

- src/modules/products/dto/create-product.dto.ts
- src/modules/products/dto/update-product.dto.ts
- src/modules/products/entities/product.entity.ts
What is this PR solving?
A superadmin can't create product due to this block of code.
```
@Column({ type: 'int', nullable: false, default: 0 })
price: number;
```
As a result the end point throws a 500 status code
What did I do in this PR:
modified the entity to float 
included the max decimal in create and update product dtos
```
@IsNumber({ maxDecimalPlaces: 2 })
@Min(0)
price: number;
```
> fix(products): float number throwing error

- src/modules/auth/auth.module.ts
- src/modules/auth/auth.service.ts
- src/modules/notifications/notifications.module.ts
- src/modules/organisations/organisations.service.ts
- src/modules/testimonials/testimonials.module.ts
- src/modules/user/user.controller.ts
- src/modules/user/user.module.ts
- src/modules/user/user.service.ts
Reverts hngprojects/hng_boilerplate_nestjs#673
> Revert "feat: Get user organizations"

- .github/workflows/dev.yml
- config/auth.config.ts
- src/app.module.ts
- src/modules/auth/auth.module.ts
- src/modules/help-center/help-center.controller.ts
- src/modules/product-category/entities/product-category.entity.ts
- src/modules/user/user.service.ts
- added redis variable to the pipeline to fix workflow failure
> feat: updated pipeline to include redis variables

- package-lock.json
- package.json
- src/guards/authorization.guard.ts
- src/helpers/SystemMessages.ts
- src/modules/products/dto/get-total-products.dto.ts
- src/modules/products/products.controller.ts
- src/modules/products/products.module.ts
- src/modules/products/products.service.ts
- src/modules/products/tests/products.service.spec.ts
Develop an API endpoint that retrieves the total number of products for the current month and compares it with the previous month's total. The response includes the total number of products and the percentage change from the previous month.
The endpoint /api/v1/products/total is accessible via a GET request.
When the request is successful, the endpoint returns a 200 OK status.
If an unexpected server error occurs, the endpoint returns a 500 Internal Server Error status.
The response body of a 500 error contains an error message indicating that an unexpected error occurred.
Ensure that all unit and integration tests for the fetch total products endpoint are comprehensive and verify the functionality correctly.
This provides a backend service that allows fetching the total number of …
> feat: create endpoint to get total products on admin dashboard

- src/helpers/custom-http-filter.ts
- src/shared/inteceptors/response.interceptor.ts
fixes the format of status code for error responses to change status to status_code
> fix: error response format

- src/guards/super-admin.guard.ts
- src/modules/organisations/organisations.service.ts
> feat: hotfix for guards

- src/helpers/SystemMessages.ts
- src/modules/blog-category/blog-category.controller.ts
- src/modules/blog-category/blog-category.service.ts
- src/modules/blog-category/dto/update-blog-category.dto.ts
- src/modules/blog-category/tests/update-blog-category.service.spec.ts
This PR updates a blog category
* Error Handling: This feat returns specific HTTP status codes and messages based on various scenarios.
> feat: update blog category

- .github/workflows/prdeploy.yml
- .github/workflows/prdeployMain.yml
ci: added deocker deployment workflow for main branch
> ci: added deocker deployment workflow for main branch

- src/guards/authorization.guard.ts
- src/guards/super-admin.guard.ts
- src/modules/auth/auth.service.ts
- src/modules/organisations/organisations.controller.ts
- src/modules/organisations/organisations.service.ts
- src/modules/organisations/tests/organisations.service.spec.ts
- src/modules/products/dto/create-product.dto.ts
- src/modules/products/products.controller.ts
- src/modules/products/products.service.ts
- fixed inconsistencies with ownership guard
- Allowed super admin access to all routes
- updated checks in the guard to cater for super admin
- Create a new organisation for user on registration with google auth
> feat: fix issues with Ownership guard

- .github/workflows/main.yml
- .github/workflows/staging.yml
- src/guards/super-admin.guard.ts
- src/modules/organisations/organisations.service.ts
- src/modules/products/products.controller.ts
- src/modules/products/products.service.ts
- Provides an endpoint for guests to access all products and view a single product
- Added pagination for fetching all products
> feat: Fetch all products and single product for guest

- src/modules/organisations/organisations.controller.ts
- src/modules/organisations/organisations.service.ts
- fixed response for creating organisation
> feat: fixed response body of create organisation endpoint

- .github/workflows/prdeploy.yml
- .github/workflows/prdeployMain.yml
ci: added docker deployment workflow for main branch
> ci: added docker deployment workflow for main branch

- src/guards/super-admin.guard.ts
- src/modules/organisations/organisations.service.ts
- src/modules/products/products.controller.ts
- src/modules/products/products.service.ts
- Implemented endpoint to fetch products of an organisation
> feat: fetch organisation products

- dora/main.py
> feat: bootstrapped dora exporter (DevOps)

- src/modules/organisations/organisations.service.ts
- fixes the bug of assigning super-admin role to normal admin
> fix: updated organisation creation service

- src/modules/auth/auth.service.ts
- src/modules/auth/tests/auth.service.spec.ts
- src/modules/organisations/mapper/organisation.mapper.ts
- src/modules/organisations/organisations.controller.ts
- src/modules/organisations/organisations.service.ts
-  Updated authentication payload to return user organisations and roles of user in each
``` json
{
"status_code": 201,
"message": "User Created Successfully",
"access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNhMmI5YTRhLTA3MTAtNGQ5Zi1iM2UwLTZkMDQxOTU1YjFhOCIsInN1YiI6ImNhMmI5YTRhLTA3MTAtNGQ5Zi1iM2UwLTZkMDQxOTU1YjFhOCIsImVtYWlsIjoidXNlcnNAa2luZ3MuY29tIiwiaWF0IjoxNzIzMjUwNTg1LCJleHAiOjE3MjMyNTQxODV9.nen3RHA1aHWcHH2bYtZCcg_uUNVCypBToUEwuVgWfbs",
"data": {
"user": {
"id": "ca2b9a4a-0710-4d9f-b3e0-6d041955b1a8",
"first_name": "John",
"last_name": "Doe",
"email": "users@kings.com",
"avatar_url": null
},
"oranisations": [
{
"organisation_id": "e12973d1-cbc3-45f8-ba13-14991e4490fa",
"name": "John's Organisation",
"user_role": "admin",
"is_owner": true
}
]
}
}
```
> feat: updated authentication response payload

- src/database/seeding/seeding.service.ts
- src/guards/authorization.guard.ts
- src/modules/auth/auth.service.ts
- src/modules/auth/tests/auth.service.spec.ts
- src/modules/blogs/blogs.controller.ts
- src/modules/faq/faq.controller.ts
- src/modules/newsletter-subscription/newsletter-subscription.controller.ts
- src/modules/organisations/organisations.service.ts
- src/modules/products/products.controller.ts
- src/modules/products/products.service.ts
- src/modules/role/entities/organisation-user-role.entity.ts
- src/modules/role/role.controller.ts
- src/modules/teams/teams.controller.ts
- Updates the response body of all authentication and registration route (including google auth) to add super admin status
- Implemented seeding for super admin
``` json
{
"message": "Login successful",
"access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI3MzY5MTcxLTAzNGMtNDQyMy1iZjc3LTQyMGQ0ZDdkNWU4NyIsInN1YiI6IjI3MzY5MTcxLTAzNGMtNDQyMy1iZjc3LTQyMGQ0ZDdkNWU4NyIsImlhdCI6MTcyMzI4NzExNywiZXhwIjoxNzIzMjkwNzE3fQ.R63FDA7Zcf5J1JHtGl7_KQHD0AxXUGjQFm5ZF3pvRX0",
"data": {
"user": {
"id": "27369171-034c-4423-bf77-420d4d7d5e87",
"first_name": "Jane",
"last_name": "Smith",
"email": "user3@admin.com",
"avatar_url": null,
"is_superadmin": true
},
"organisations": [
{
"organisation_id": "",
"user_role": "super-admin",
"is_owner": ""
}
]
}
}
```
> feat: Update authentication response

- src/modules/waitlist/dto/create-waitlist-response.dto.ts
- src/modules/waitlist/dto/create-waitlist.dto.ts
- src/modules/waitlist/dto/get-waitlist.dto.ts
- src/modules/waitlist/dto/waitlist-error-response.dto.ts
- src/modules/waitlist/tests/waitlist.service.spec.ts
- src/modules/waitlist/waitlist.controller.ts
- src/modules/waitlist/waitlist.service.ts
**Description**:  
This PR closes #106 and implements an API endpoint `/api/v1/waitlist` for receiving and storing user information submitted through the waitlist signup form on the website. The endpoint validates and sanitizes incoming user data, securely stores the information in the database, and sends a confirmation email to the user upon successful signup. 
**What does the PR do?**:  
This PR implements a POST endpoint at `/api/v1/waitlist` for waitlist signups. The endpoint performs the following functions:
- Accepts user data through a POST request.
- Validates email format and ensures the `email` and `name` fields are provided.
- Sanitizes and securely stores the user information in the database.
- Sends a confirmation email to the user upon successful signup.
- Handles errors …
> feat: create waitlist api endpoint

- .env.local
- src/modules/profile/profile.controller.ts
- src/modules/profile/profile.service.ts
This fix resolves the base URL of the user uploaded profile picture
> fix: upload profile picture

- package-lock.json
- package.json
- src/helpers/SystemMessages.ts
- src/helpers/app-constants.ts
- src/modules/profile/dto/file.validator.ts
- src/modules/profile/dto/upload-profile-pic.dto.ts
- src/modules/profile/profile.controller.ts
- src/modules/profile/profile.service.ts
- src/modules/profile/tests/profile.service.spec.ts
This fix resolves the base URL of the user uploaded profile picture
> fix: profile pic

- src/app.e2e.spec.ts
- src/database/seeding/seeding.service.ts
- src/modules/auth/auth.controller.ts
- src/modules/auth/tests/auth.service.spec.ts
- src/modules/blogs/blogs.service.ts
- src/modules/notifications/dtos/mark-all-notifications-as-read.dto.ts
- src/modules/products/products.controller.ts
- src/modules/profile/dto/upload-profile-pic.dto.ts
- src/modules/profile/profile.controller.ts
- src/modules/profile/profile.service.ts
- src/modules/profile/tests/profile.service.spec.ts
- src/modules/role/role.controller.ts
This fix solves the swagger docs file object
> fix:upload profile pic

- src/modules/profile/entities/profile.entity.ts
- src/modules/profile/profile.service.ts
- src/modules/profile/tests/profile.service.spec.ts
This fix changes profile_pic_url to avatar_url
> fix: implemented fix for profile picture

- .github/workflows/staging-deployment.yaml
- fix the issue in staging workflow file
> feat: fix issue with staging deployment

- src/modules/auth/auth.controller.ts
- src/modules/auth/auth.service.ts
- Added support for verifying id token generated from mobile devices
> feat: added google auth support for mobile devices

- src/modules/faq/faq.controller.ts
- src/modules/faq/faq.module.ts
- src/modules/faq/faq.service.ts
- src/modules/faq/test/faq.create.service.spec.ts
- src/modules/faq/test/faq.service.spec.ts
---
This PR enhances the Faq module by adding translation support for all CRUD (Create, Read, Update, Delete) operations. The translation functionality ensures:
- FAQs can be created, updated, and retrieved in multiple languages.
- The content of FAQs is automatically translated into the user's preferred language when creating or updating an FAQ.
- All responses from the FAQ module are translated based on the `Accept-Language` header provided by the client.
- Fallback mechanisms are in place to ensure the default language (English) is used if no translation is available for the specified language.
1. Ensure you have a valid user token.
2. Test each CRUD operation for FAQs with the `Accept-Language` header set to different languages, such as `fr` (French) or `es` (Spanish).
- **Create an …
>  feat : Added Translation for FAQ Module

- src/modules/billing-plans/billing-plan.controller.ts
- src/modules/products/products.service.ts
**Description**:
This PR introduces an existing `SuperAdminGuard` to restrict access to the creating a new billing plan. This guard ensures that only users with the `SuperAdmin` role can create billing plans, adding an additional layer of security to our billing management process.
1. **SuperAdminGuard Implementation**:
- Using an existing `SuperAdminGuard` that checks the role of the authenticated user.
- The guard verifies that the user has the `SuperAdmin` role before allowing access to the POST endpoint.
2. **Controller Modification**:
- Updated the `BillingPlansController` to apply the `SuperAdminGuard` to the POST endpoint for creating or updating billing plans.
- Applied the guard using the `@UseGuards(SuperAdminGuard)` decorator.
**Testing**:
- **Manual Testing**:
- Verified that …
> fix: billing plans protection

- package-lock.json
- package.json
- src/app.module.ts
- src/modules/api-status/api-status.controller.ts
- src/modules/api-status/api-status.module.ts
- src/modules/api-status/api-status.service.ts
- src/modules/api-status/dto/create-api-status.dto.ts
- src/modules/api-status/dto/create-request.dto.ts
- src/modules/api-status/entities/api-status.entity.ts
- src/modules/api-status/entities/request.entity.ts
- src/modules/api-status/tests/api-status.service.spec.ts
- src/modules/billing-plans/billing-plan.module.ts
> This PR adds two new endpoints for adding and retriving the health status of all endpoints which are available on POST /api/v1/api-status for send health status for various endpoints and GET /api/v1/api-status for retriving the health status of all endpoints. 
<hr>
GET /api/v1/api-status 
##Request Body
```
No Body Required
```
Response:
```
{
"message": "Health Status Retrieved Successfully",
"data": [
{
"id": "e4b28f77-8872-4669-8821-0f4a6774015c",
"created_at": "2024-08-24T00:01:14.964Z",
"updated_at": "2024-08-24T00:01:14.964Z",
"api_group": "Authentication API",
"status": "down",
"lastChecked": "2024-08-24T00:01:14.964Z",
"details": "All tests passed",
"requests": [
{
"id": "4e75ed77-9da0-44ba-b545-a8028a3f6595",
"created_at": "2024-08-24T00:01:15.065Z", …
```
> feat: adds api-status for health check of all endpoints

- src/modules/auth/auth.service.ts
- src/modules/auth/tests/auth.service.spec.ts
- Fix inconsistency with frontend changing client id
- Migrated to using google api url to validate id token
[Link to issue](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/800)
> feat: updated google authentication logic to fix inconsistencies

- src/modules/billing-plans/billing-plan.service.ts
removed unwanted try catch blocks in the billing-plans module's controller
> refactor(billing plans): remove try catch blocks

- src/modules/jobs/docs/jobs-swagger.ts
The swagger tags for the jobs module were moved to a dedicated folder
> fix(jobs): reformat swagger tags for jobs module

- package.json
- src/modules/comments/comments.controller.ts
- src/modules/comments/comments.service.ts
**What does the PR do?**
This PR introduces new API endpoints to get a comment. It includes server-side logic for handling comment fetching, along with appropriate validation and error handling.
How should this be manually tested?
**To Get a Comment:**
Send a GET request to /api/v1/comments/:comment_id and a valid comment_id in the request.
Example:
`GET /api/v1/comments/:comment_id`
Successful Response
On a successful comment fetching, the API should return a 200 SUCCESS status code.
```json
{
"status": "status_code",
"message": "Comment retrieved successfully",
"data": {
"id": "84488317-234b-41b5-a2d1-07d47a50be8e",
"created_at": "2024-08-08T06:27:40.309Z",
"updated_at": "2024-08-08T06:59:59.030Z",
"comment": "I just update this comment now",
"model_id": "1234",
"model_type": "post"
} …
```
> feat: get a single comment

- src/modules/jobs/jobs.controller.ts
- exposed job endpoint to allow fetching on external page
> feat: Job Fetching

- src/database/data-source.ts
- fix connection issues with database on startup
- Added port variable to database configuration
> fix: Database connection error
