hngprojects/hng_boilerplate_nestjs

src/modules/user/dto/deactivate-account.dto.ts
src/modules/user/tests/user.service.spec.ts
src/modules/user/user.controller.ts
src/modules/user/user.service.ts

Closes: Issue #65
This PR introduces the functionality for deactivating user accounts. It ensures that users are properly authenticated and that their accounts are correctly updated in the database. Additionally, it includes an email notification to inform users about the account deactivation.
1. **Authenticate a User**:
- Send a `POST` request to `/api/v1/auth/login` to authenticate a user and obtain a JWT token.
2. **Deactivate User**:
- Send a `PATCH` request to `/api/v1/accounts/deactivate` with the following request body:
```json
{
"confirmation": true,
"reason": "your reason to deactivate"
}
```
```json
{
"message": "Account Deactivated Successfully" 
}
```
- Ensure that the user account status is updated to deactivated in the database.
- Verify that the user …

feat: deactivate user account

---

src/modules/user/dto/get-user-data-by-id-response.dto.ts
src/modules/user/tests/user.service.spec.ts
src/modules/user/user.controller.ts
src/modules/user/user.service.ts

This PR is about getting a user by Id
Send a GET request to `/api/v1/users/:userId` with access token in the authorization header.
#81

feat: get user by id

---

src/modules/auth/auth.controller.ts

This PR changes the intial endpoint for signing with magic link feature from signin-token and verify-signin-token to magic-link and magic-link/verify respectively. This is to comply with the generally agreed url specifications for all endpoint by the team starlight backend developers.

fix: change endpoint urls for login with magic link

---

src/modules/products/products.service.ts
src/modules/products/tests/products.service.spec.ts

This PR fixes an issue in the endpoint for creating a new product:
* Added the organization that created the new products.
**Success**
```json
{
"status_code": 201,
"message": "Product created successfully",
"data": {
"id": "ecb968ce-f7e0-4ff9-913b-0c8dbe9d3f46",
"name": "Second product",
"description": null,
"price": 45,
"status": "in stock",
"quantity": 7,
"created_at": "2024-07-29T19:51:39.004Z",
"updated_at": "2024-07-29T19:51:39.004Z"
}
}
```
Link to this issue: [#[FEAT]: CREATE PRODUCTS API ENDPOINT #203](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/203)

fix: create product

---

package-lock.json
src/app.module.ts
src/main.ts
src/run-tests/python.py
src/run-tests/run-tests.controller.ts
src/run-tests/run-tests.module.ts
src/run-tests/run-tests.service.spec.ts
src/run-tests/run-tests.service.ts

This PR implements an API endpoint in the NestJS application to run compatibility tests using a Python script. The script simulates testing various API endpoints and streams the output to the user on the browser.
1. **Start the NestJS server:**
Ensure your NestJS server is running.
2. **Open the path on the browser**
Navigate to `BASE_URL/run-tests` in the browser.
3. **Observe the response:**
The server should stream the output from the Python script in real-time. The response should look like this:
```
Starting the test script...
Running tests...
Test 1: Success
Test 2: Failed
All tests completed.
Exiting script...
```
- Ensure the Python script (`python.py`) is executable and available in the project directory.
- The Python script used for testing is a placeholder and can be replaced …

feat: run python script on server and display in browser

---

src/modules/organisations/dto/org-members-response.dto.ts
src/modules/organisations/mapper/org-members.mapper.ts
src/modules/organisations/organisations.controller.ts
src/modules/organisations/organisations.service.ts
src/modules/organisations/tests/organisations.service.spec.ts

Implements backend functionality for retrieving users belonging to a particular organisation, accessible only to a member of that organisation.
[Link to GitHub Issue #79](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/79)
- The endpoint should be accessible at `api/v1/organization/:org_id/users`
- The endpoint should accept HTTP GET requests.
- The endpoint should be secured to ensure that only authenticated users can fetch users in the organization
- The endpoint should check that the user is a member of the organization
- The endpoint should check that the organisation Id in the url path is an existing organization
- Requests to the endpoint must include a valid authentication token in the Authorization header. Authorization: Bearer <token>
GET …

feat: Get all members in an organization

---

package-lock.json
src/app.module.ts
src/database/seeding/seeding.service.ts
src/main.ts
src/modules/invite/tests/invite.service.spec.ts
src/modules/jobs/tests/job.service.spec.ts
src/modules/notifications/dtos/create-notification-response.dto.ts
src/modules/notifications/dtos/mark-notification-as-read-error.dto.ts
src/modules/notifications/dtos/mark-notification-as-read.dto.ts
src/modules/notifications/dtos/notification-data.dto.ts
src/modules/notifications/dtos/notification-response.dto.ts
src/modules/notifications/entities/notifications.entity.ts
src/modules/notifications/notifications.controller.ts
src/modules/notifications/notifications.module.ts
src/modules/notifications/notifications.service.ts
src/modules/notifications/tests/mocks/notification-repo.mock.ts
src/modules/notifications/tests/mocks/update-notification-to-isRead.ts
src/modules/notifications/tests/notifications.service.spec.ts
src/modules/organisations/tests/mocks/organisation.mock.ts
src/modules/user/entities/user.entity.ts

This feature allows users to mark a specific notification as read. The endpoint takes a notification ID as a parameter and updates the is_read status of the notification.
How should this be manually tested?
1. Login to a user account, and get the access token
2. Make a PATCH request to the `\api\v1\notifications\{notification_id}` endpoint with the following payload:
```json
Authorization: Bearer <access_token>
{
" is_read": true
}
```
Successful Response
On a successful notification update, the API should return a 200 status code.
```json
{
"data": {
"notification_id": "uuid",
"is_read": true,
"updated_at": "2024-07-28T12:00:00Z"
}
}
```
Authentication Error:
When the current user is not properly authenticated to change the organization detail: …

feat: mark single notification as read

---

package-lock.json
package.json
src/guards/authorization.guard.ts
src/modules/jobs/dto/job.dto.ts
src/modules/jobs/entities/job.entity.ts
src/modules/jobs/guards/job.guard.ts
src/modules/jobs/jobs.controller.ts
src/modules/jobs/jobs.service.ts
src/modules/jobs/tests/job.guard.spec.ts
src/modules/jobs/tests/jobs.service.spec.ts

**Issue**: The job creation process encountered an error due to incorrect input data handling. Inputs with salary ranges above 150k were causing internal server errors.
This was causing failures in creating new job listings and impacting the user experience.
**Changes Made**:
**Test Screenshots**:
**Notes**:
- Ensure review of the changes in `job.dto.ts` and `job.entity.ts` for the specific updates in handling job creation.
Please review the changes and provide feedback.

fix: create job error

---

src/modules/organisation-role/dto/create-organisation-role.dto.ts
src/modules/organisation-role/dto/update-organisation-role.dto.ts
src/modules/organisation-role/entities/organisation-role.entity.ts
src/modules/organisation-role/organisation-role.controller.ts
src/modules/organisation-role/organisation-role.module.ts
src/modules/organisation-role/organisation-role.service.ts
src/modules/organisation-role/test/orgainisation-role.serviec.spec.ts

This PR introduces a new endpoint to retrieve all roles in an organization. 
Send a GET request to `/api/v1/organisation/{org_id}/roles`.
Implement GET `/api/v1/organisation/{org_id}/roles` endpoint
[FEAT] API Endpoint to Fetch All Roles within an Organisation. #288

feat: API Endpoint to Fetch All Roles within an Organisation

---

.env.local
.vscode/settings.json
package-lock.json
src/modules/faq/faq.controller.spec.ts
src/modules/faq/faq.controller.ts
src/modules/faq/faq.service.spec.ts
src/modules/faq/faq.service.ts
src/modules/faq/update-faq.dto.ts

This PR addresses issue #170 by implementing the get, update and delete frequently asked questions operations from the 
database. 
To test this feature, you can send a GET request to the following endpoint:
Endpoint:
` GET /api/v1/faqs`
Response (Success):
```
[
{
"id": "String",
"question": "String",
"answer": "String",
"category": "String"
}
]
```
Response (Error - Invalid Request):
```
{
"message": "Invalid request",
"status_code": 400
}
```
Endpoint:
` PUT /api/v1/faqs/{id}`
Request Body:
```
{
"question": "String",
"answer": "String",
"category": "String"
}
```
Response (Success):
```
{
"id": "String",
"question": "String",
"answer": "String",
"category": "String"
}
```
Response (Error - Invalid Request):
```
{
"message": "Invalid request data",
"status_code": 400
}
```
Response …

feat : faq crud operations

---

src/app.module.ts
src/modules/help-center/Tests/help-center.service.spec.ts
src/modules/help-center/dto/create-help-center.dto.ts
src/modules/help-center/dto/update-help-center.dto.ts
src/modules/help-center/entities/help-center.entity.ts
src/modules/help-center/help-center.controller.ts
src/modules/help-center/help-center.module.ts
src/modules/help-center/help-center.service.ts

This PR implements an endpoint for permanently deleting outdated or invalid help center topics from the database:
- **Added DELETE /api/v1/help-center/topics/:id Endpoint:** Allows superadmins to delete existing topics.
- **Authentication and Authorization:** Requires a JWT token and superadmin role for access.
- **Response Handling:** Provides appropriate responses for various authorization and validation scenarios.
1. **Login Superadmin User:**
- Make a `POST` request to `/api/v1/auth/login` with a superadmin user's credentials.
- Check the response for a valid JWT token.
2. **Delete Help Center Topic:**
- Make a `DELETE` request to `/api/v1/help-center/topics/:id` with the topic ID in the path parameter and a valid JWT token in the header.
- Verify the response confirms the topic has …

feat: delete help center topics

---

src/modules/invite/invite.controller.ts
src/modules/organisation-permissions/mocks/organisation.mock.ts
src/modules/organisation-permissions/organisation-permissions.controller.ts
src/modules/organisation-permissions/organisation-permissions.service.ts
src/modules/organisation-permissions/tests/organisation-permissions.service.spec.ts
src/modules/organisation-role/organisation-role.controller.ts
src/modules/organisation-role/organisation-role.service.ts
src/modules/organisation-role/tests/organisation-role.service.spec.ts
src/modules/organisations/dto/update-organisation.dto.ts
src/modules/organisations/organisations.controller.ts
src/modules/organisations/organisations.service.ts
src/modules/products/products.controller.ts
src/modules/user/tests/user.service.spec.ts
src/modules/user/user.service.ts

This pull request fixes a spelling inconsistency in the codebase. The word 'Organizations' has been changed to 'Organisations' to maintain consistency throughout the codebase.
- Create a new user
- Login with the new user account.
- Successful login
- Replace all occurence of 'Organizations' with 'Organisations'

fix: organization spelling inconsistency

---

src/modules/products/products.controller.ts
src/modules/products/products.service.ts

This PR is to get a product by id
Send  `GET` request to `/api/v1/organizations/{:org-id}/products/{:product-id}`
- **Response:**
**On successful retrieval:**
```json
{
"message": "Product details retrieved successfully",
"data": {
"id": 1,
"name": "string",
"price": 45.0
"description": "string",
}
}
```
**On error (e.g., product not found):**
```json
{
"status": "error",
"message": "Product not found",
"status_code": 404
}
```
**On error (e.g., unauthorized access):**
```json
{
"status": "error",
"message": "Unauthorized access",
"status_code": 401
}
```
[[FEAT] API Endpoint to Fetch All Roles within an Organisation](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/152)

feat: get product by id

---

src/modules/organisation-role/organisation-role.controller.ts
src/modules/organisation-role/organisation-role.service.ts
src/modules/organisation-role/tests/organisation-role.service.spec.ts

This PR introduces an endpoint for updating a role within an organization.
Make a `PATCH` request to the endpoint `/api/v1/organisations/{org_id}/roles/{role_id}` with a request body matching this:
```jsonc
{
"name": "updated role", // the role name
"description": "updated description" // a description of the role
}
```
```json
{
"data": {
"id": "string",
"name": "string",
"description": "string"
}
}
```
**400 Bad Request:**
```json
{
"status_code": 400,
"error": "Bad Request",
"message": "Invalid role ID format or input data"
}
```
**404 Not Found (Role):**
```json
{
"status_code": 404,
"error": "Role not found",
"message": "The role with ID ${id} does not exist"
}
```
**404 Not Found (Organization):**
```json
{
"status_code": 404,
"error": "Organisation not found", …
```

feat: update role within an organisation

---

src/modules/auth/auth.service.ts
src/modules/auth/dto/updatePasswordDto.ts
src/modules/email/templates/reset-password.hbs
src/modules/otp/otp.service.ts
src/modules/user/entities/user.entity.ts

This PR fixes the endpoints to handle password reset requests for registered users who have forgotten their passwords. The endpoint ensures secure password updates by validating necessary fields, verifying tokens. On successful password reset, a 200 status code is returned along with a success message. Appropriate error statuses are returned in case of errors.
Endpoints:
[POST] /api/v1/auth/forgot-password
Description: Initiates password reset process by verifying the user's email and sending a reset token.
Request Body: { "email": "string" }
Responses:
200 OK: If a user with that email exists, a password reset link is sent.
400 Bad Request: Invalid email.
500 Internal Server Error: Server error.
[POST] /api/v1/auth/reset-password
Description: Resets the user's password using the received …

fix: existing endpoints for reseting password

---

src/guards/member.guard.ts
src/guards/permission.decorator.ts
src/modules/organisation-permissions/entities/permissions.entity.ts
src/modules/organisation-permissions/organisation-permissions.service.ts

This PR has the member guard which checks if the user is the owner/creator or if they have the necessary permissions to perform an operation
- add it to an endpoint that requires this validation. For example,
```
@UseGuard(MembershipGuard)
@Permissions(PermissionCategory.CanAddProducts)
@Post('/products')
async createProduct(){}
```
If the user has the necessary permissions, they are allowed to proceed with the operation
- Organisation does not exist
```
{
message: "Organisation not found",
status: 404
}
```
- User does not have the necessary permissions
```
{
"message": "You dont have the permission to perform this action",
"status": 403
}
```
[Link to Issue on Linear](https://linear.app/team-bingo/issue/BAC2-192/create-member-guard)

feat: creating the member guard

---

src/modules/user/tests/user.service.spec.ts
src/modules/user/user.controller.ts
src/modules/user/user.service.ts

**What is this PR solving?**
- A superadmin can't get the list of all users do to this block of code.
- As a result the end point returns a 403 status code
**What did I do in this PR:**
-  Added the super admin guard to the get-all users controller
- Removed the code block that was checking for the user role, as the guard takes care of that
- Updated the service spec file to adjust to these new changes
***Screenshot testing the endpoint after the changes (with a user that is a super-admin):***
***Screenshot testing the endpoint after the changes (with a user that is NOT a super-admin):***
**How to test this PR?**
1- Login with a account that has super admin role
2- Fetch the endpoint ```GET /api/v1/users```
Reference Issue 651: [Link to …

fix: get all users 

---

src/modules/products/products.controller.ts
src/modules/products/products.module.ts
src/modules/products/products.service.ts
src/modules/products/tests/products.service.spec.ts

This PR implements an endpoint for fetching the current stock of a product
An authenticated user who is a member, owner or creator of the organisation specified by id  can send a `GET` request to `/api/v1/organizations/{org_id}/product/{product_id}/stock`
- On success:
```bash
"message": "Product stock retrieved successfully",
"data": {
"product_id": "8yf55648-1a26-4ab0-8941-a7843db1e1bc",
"current_stock: 10,
"last_updated": "2024-07-29T22:59:10.052Z",
}
}
```
Find the link to the issue [here](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/284)

feat: get product stock

---

src/modules/profile/entities/profile.entity.ts
src/modules/profile/profile.controller.ts
src/modules/profile/profile.service.ts
src/modules/profile/tests/profile.service.spec.ts

This PR implements an endpoint for deleting user profile:
* Added DELETE /api/v1/profile/:id Endpoint: Deletes a user's profile
* Authentication: Ensures only authenticated users can access these endpoints.
* Authorization: Ensures only users or admin can access this route.
* Error Handling: Returns specific HTTP status codes and messages based on various scenarios.
**Success**
```json
{
"message": "User profile deleted successfully"
}
```
Link to this issue: [FEAT Create API Endpoints to Delete User Profile](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/167)

feat: delete user profile

---

src/helpers/http-exception-filter.ts
src/main.ts
src/modules/organisations/dto/org-member.dto.ts
src/modules/organisations/entities/org-members.entity.ts
src/modules/organisations/organisations.controller.ts
src/modules/organisations/organisations.service.ts
src/modules/organisations/tests/organisations.service.spec.ts

It removes a member from an organisation
- On success, the API should return a `204 No Content` status code with the success message.
- On failure, the API should return a 400 Bad Request status code with appropriate error messages.
```json
{
"message": "User removed from organisation successfully",
"status_code": 200
}
```
```json
{
"status": "Bad Request",
"message": "Bad request error",
"status_code": 400
}
```
```json
{
"status": "Unauthorized",
"message": "User not authenticated",
"status_code": 401
}
```
```json
{
"status": "Forbidden",
"message": "Only owners can add users",
"status_code": 403
}
```
Link to issue #173

feat: remove member from organisation

---

src/helpers/SystemMessages.ts
src/modules/testimonials/dto/get-testimonials.dto.ts
src/modules/testimonials/mappers/testimonial.mapper.ts
src/modules/testimonials/testimonials.controller.ts
src/modules/testimonials/testimonials.service.ts
src/modules/testimonials/tests/mocks/testimonials.mock.ts
src/modules/testimonials/tests/testimonials.service.spec.ts

This PR returns the specified user's testimonials
1. Login to an account using the `api/v1/auth/login`
2. Retrieve testimonials using the `/api/v1/testimonials/:user_id`
3. You can also add query parameters for the `page` and `page_size`
```
{
"status": 200,
"message": "User's testimonials successfully retrieved",
"data": {
"user_id": "user-123",
"testimonials": [
{
"id": "testimonial-12",
"name": "Jane Doe",
"content": "Excellent work!",
"created_at": "2024-07-08T23:45:00Z"
}
]
},
"pagination": {
"page": 1,
"pageSize": 1,
"total_pages": 1
}
}
```
```
{
"status": 400,
"message": "User has no testimonials"
}
```
[Link to Linear Issue](https://linear.app/team-bingo/issue/BAC2-195/retrieve-all-the-users-testimonials)
[Link to GitHub …

feat: get user testimonials

---

src/modules/products/products.superadmin.controller.ts

Develop a new endpoint that allows a Super-Admin to add a new product to the system. This endpoint should ensure that only users with Super-Admin privileges can access it. 
###Acceptance Criteria###
##Endpoint URL##
##POST##
`/api/super-admin/products`
*Request Headers*
Authorization: SuperadminGuard
Content-Type: application/json
*Request Body*
```json
{
"name": "Product Name",
"description": "Product Description",
"price": 100.0,
"category": "Product Category",
"availability": true
}
```
*Response*
-Success (201 Created)
```json
{
"message": "Product added successfully",
"product": {
"id": "Product ID",
"name": "Product Name",
"description": "Product Description",
"price": 100.0,
"status": "in stock",
"quantity": "20",
"createdAt": "Timestamp",
"updatedAt": "Timestamp"
}
}
```
-Error …

feat: create endpoint for Add a Product for Super-admin

---

package.json
src/modules/organisations/organisations.controller.ts
src/modules/organisations/organisations.service.ts
src/modules/organisations/tests/organisations.service.spec.ts

**What does this PR do?**
This PR introduces an endpoint that enables the export of organisation members to a CSV file. The endpoint will generate a CSV file containing details of all members in an organisation, including their ID, name, email, and role.
**How to Test**
**Export Organisation Members to CSV:**
- Use the endpoint `GET /api/v1/organisations/:org_id/members/export` to export members of an organisation by their organisation ID.
**Verify CSV Export:**
- Check if the CSV file is created with the expected headers (ID, Name, Email, Role) and member data.
- Ensure that the file is downloadable and the data matches the organisation members' details in the database.
**Edge Cases**
- Test whether the organisation exists before attempting to export members.
- Test the behaviour of the …

feat: export organization members

---

src/app.module.ts
src/database/seeding/seeding.controller.ts
src/database/seeding/seeding.service.ts
src/helpers/SystemMessages.ts
src/modules/invite/mocks/mockUser.ts
src/modules/notifications/tests/mocks/notification-repo.mock.ts
src/modules/organisations/tests/mocks/organisation.mock.ts
src/modules/organisations/tests/mocks/user.mock.ts
src/modules/products/entities/product.entity.ts
src/modules/products/products.module.ts
src/modules/products/products.service.ts
src/modules/products/tests/mocks/deleted-product.mock.ts
src/modules/products/tests/mocks/product.mock.ts
src/modules/products/tests/products.service.spec.ts
src/modules/revenue/dto/get-revenue-response.dto.ts
src/modules/revenue/entities/cart.entity.ts
src/modules/revenue/entities/order-items.entity.ts
src/modules/revenue/entities/order.entity.ts
src/modules/revenue/entities/transaction.entity.ts
src/modules/revenue/revenue.controller.ts
src/modules/revenue/revenue.module.ts
src/modules/revenue/revenue.service.spec.ts
src/modules/revenue/revenue.service.ts
src/modules/subscriptions/subscriptions.controller.ts
src/modules/user/entities/user.entity.ts
src/modules/user/tests/mocks/user.mock.ts

This PR is about creating an endpoint to generate revenue for the company. The endpoint handles the creation of orders, order items, carts, and transactions by seeding the data. The endpoint returns errors if:
How should this be manually tested?
1. Login to a user account and get the access token.
2. Run the `/api/v1/seed/transactions`
3. Make a POST request to the `/api/v1/revenue` endpoint with the token:
```json
Authorization: Bearer <access_token>
```
Successful Response
On a successful revenue fetch, the API should return a 200 Okstatus code.
```json
{
{
"message": "Revenue Fetched",
"data": {
"totalRevenueCurrentMonth": 4500,
"revenuePercentChange": "55.56%"
}
}
```
Authentication Error:
When the current user is not properly authenticated:
```json
{
"message": …
```

feat: Add functionality to get Revenue

---

src/modules/user/entities/user.entity.ts
src/modules/user/tests/user.service.spec.ts
src/modules/user/user.controller.ts
src/modules/user/user.service.ts

closes #167 
**What does this PR do?**
This PR introduces an endpoint that enables the soft deletion of users from the system. The endpoint will mark a user as inactive instead of permanently deleting them, allowing for the recovery of the user’s data if needed.
**How to Test**
1. **Soft Delete a User**:
- Use the endpoint `DELETE /api/v1/users/:user_id` to soft delete a user by their user ID.
2. **Verify Soft Deletion**:
- Check if the user’ is deleted from db.
- Ensure that the user is no longer retrievable through the regular user retrieval endpoints.
**Edge Cases**
- Test whether the user exists before attempting to soft delete.
- Test whether the user has already been soft deleted.
- Test the behavior of the system when trying to soft delete a user that does not exist.
**Checklist** …

feat: user soft deletion

---

src/modules/auth/auth.service.ts

This PR ensures that the forgot password email send a link to the frontend user interface instead of the backend endpoint
1. Request to change your password by sending a request to `api/v1/auth/forgot-password`
2. Check your email and click the link
3. You should be re-directed to the FE page
#1085

fix: correcting link in forgot password

---

src/helpers/SystemMessages.ts
src/modules/billing-plans/billing-plan.controller.ts
src/modules/billing-plans/billing-plan.service.ts
src/modules/billing-plans/docs/billing-plan-docs.ts
src/modules/billing-plans/dto/update-billing-plan.dto.ts

#Closes: #1100 
This PR introduces new functionality for updating and deleting billing plans. It adds endpoints for modifying existing billing plans and removing them from the database. The `updateBillingPlan` method allows for partial updates to a billing plan, and the `deleteBillingPlan` method handles the deletion of a billing plan by ID. Additionally, Swagger API documentation has been enhanced with custom decorators for better reusability and cleaner code.
**How should this be manually tested?**
1. **Test the `updateBillingPlan` Endpoint:**
- Send a `PATCH` request to `/billing-plans/:id` with a valid billing plan ID and an updated payload.
- Verify that the billing plan is updated correctly in the database.
- Test with an invalid billing plan ID to ensure that it returns a `404 Not …

fix: billing docs and added update and delete endpoints
